name: CI_build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Set up V version latest
      uses: vlang/setup-v@v1
      with:
          check-latest: true

    - name: Checkout repo ${{ github.event.repository.name }}
      uses: actions/checkout@v3

    - name: Build repository app
      run: v -cc clang -g -d static_boehm -gc boehm -keepc -enable-globals -shared -d no_backtrace -cflags -cflags -I"D:\a\NppLspClient\NppLspClient" .
